<?php

namespace AppBundle\Repository;

/**
 * IntegrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntegrationRepository extends \Doctrine\ORM\EntityRepository
{
}
