<?php

namespace AppBundle\Repository;

/**
 * MaintientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaintientRepository extends \Doctrine\ORM\EntityRepository
{
}
