<?php

namespace AppBundle\Repository;

/**
 * MaintientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaintientRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateStatus($status,$idUser)
    {
        $qBDelege = $this->getEntityManager()->createQueryBuilder();
        $qBDelege->update('AppBundle:Maintient', 'd')
            ->set('d.maintientStatus', $status)
            ->where('d.employerId = :idUser')
            ->setParameter('idUser', $idUser)
            ->getQuery()
            ->execute();
    }
}
