<?php

namespace AppBundle\Repository;

/**
 * TitularisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitularisationRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateStatus($status,$idUser,$id)
    {
        $qBDelege = $this->getEntityManager()->createQueryBuilder();
        $qBDelege->update('AppBundle:Titularisation', 'd')
            ->set('d.titularisationStatus', $status)
            ->where('d.employerId = :idUser')
            ->andWhere('d.id = :id')
            ->setParameter('idUser', $idUser)
            ->setParameter('id', $id)
            ->getQuery()
            ->execute();
    }
}
