app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

accueil:
    type: rest
    resource: AppBundle\Controller\DefaultController

employers:
    type: rest
    resource: AppBundle\Controller\EmployerController

users:
    type: rest
    resource: AppBundle\Controller\UserController