app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

accueil:
    type: rest
    resource: AppBundle\Controller\DefaultController

employers:
    type: rest
    resource: AppBundle\Controller\EmployerController

information:
    type: rest
    resource: AppBundle\Controller\InformationController

integration:
    type: rest
    resource: AppBundle\Controller\IntegrationController